config/routes.rb
Rails.application.routes.draw do
  root to: 'bikes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bikes do
    resources :limitations, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  has_many :customization_categories
  # has_many :customization_options, through: :customization_categories
  has_many :orders


  validates :name, presence: true
  accepts_nested_attributes_for :customization_categories, reject_if: lambda { |attributes| attributes['bike_element'].blank? }

end

app/models/customization_category.rb
class CustomizationCategory < ApplicationRecord
  belongs_to :bike
  has_many :customization_options
  has_many :limitations

  validates :bike_element, presence: true, allow_blank: false

  accepts_nested_attributes_for :customization_options, reject_if: lambda { |attributes| attributes['option'].blank? }
end

app/models/customization_option.rb
class CustomizationOption < ApplicationRecord
  belongs_to :customization_category
  # has_many :limitations


end

app/models/limitation.rb
class Limitation < ApplicationRecord
  belongs_to :customization_option
  belongs_to :customization_category
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :bike
  belongs_to :user
  has_many :purchased_customizations
end

app/models/purchased_customization.rb
class PurchasedCustomization < ApplicationRecord
  belongs_to :bike
  belongs_to :customization_option
  # belongs_to :customization_category, through: :customization_option
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController

  def index
    @bikes = Bike.all
  end

  def new
    @bike = Bike.new
    3.times do
      category = @bike.customization_categories.build
      3.times { category.customization_options.build }
    end
  end

  def create
    @bike = Bike.new(bike_params)
    if @bike.save
      redirect_to new_bike_limitation_path(@bike)
    else
      render :new
    end
  end

  def show
    @bike = Bike.find(params[:id])
  end

  def destroy
    @bike = Bike.find(params[:id])
    @bike.destroy
  end

  private

  def bike_params
    params.require(:bike).permit(
      :name,
      customization_categories_attributes: [
        :bike_id,
        :bike_element,
        customization_options_attributes: [
          :customization_category_id,
          :option
        ]
      ]
    )
  end
end

app/controllers/limitations_controller.rb
class LimitationsController < ApplicationController

  def new
    @bike = Bike.find(params[:bike_id])
    @limitation = Limitation.new
  end

  def create
    @bike = Bike.find(params[:bike_id])
    @limitation = Limitation.new(limitations_params)
  end

  private

  def limitations_params
    params.require(:limitation).permit(:customization_category_id, :customization_option_id, :allowed_options_ids)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1570608225746-6dd315e5dda3?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2484&q=80);">
  <div class="container">
    <h1>Pandabize</h1>
    <p>Your favorite bike shop, now online!</p>
  </div>
</div>

<div class="container">
  <% @bikes.each do |bike| %>
    <div class="card">
      <div class="card-body d-flex justify-content-between">
        <h5><%=  bike.name %></h5>
        <p><%= link_to "customize this bike", bike %></p>
      </div>
    </div>
  <% end %>

  <%= link_to "add new", new_bike_path, class: "button-primary"  %>
</div>

app/views/bikes/new.html.erb
<div class="container">
  <%= simple_form_for(@bike) do |f|  %>
    <%= f.input :name, label: 'Bike model name'  %>
    <%= f.simple_fields_for :customization_categories do |cc|  %>
      <hr><div class="d-flex">
        <div>
          <%= cc.input :bike_element  %>
        </div>
        <div>
          <%= cc.simple_fields_for :customization_options do |co|  %>
            <%= co.input :option  %>
          <% end %>
        </div>
      </div>
    <% end %>
    <%= f.submit  %>
  <% end %>
</div>

app/views/bikes/show.html.erb
<div class="container">
  <h2><%= @bike.name  %></h2>
  <div>
    <% @bike.customization_categories.each do |cc|  %>
      <div class="d-flex">
        <p><%= cc.bike_element %> &nbsp</p>
          <% cc.customization_options.each do |co|  %>
          <p><%= co.option %> &nbsp</p>
          <% end %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PandabizeBikes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/limitations/new.html.erb
<div class="container">
  <div class="d-flex">
    <p>Bike Model :</p>
    <%= @bike.name  %>
  </div>
  <div class="">
    <% @bike.customization_categories.each do |cc|  %>
      <hr><div class="d-flex">
        <p>Bike Part :</p>
        <%= cc.bike_element  %>
      </div>
      <% cc.customization_options.each do |co| %>
        <div class="d-flex justify-content-between">
          <p>Size/Color :</p>
          <%= co.option  %>
          <%= simple_form_for([@bike, @limitation]) do |bl|   %>
            <div class="d-flex justify-content-between">
              <p>Dependent customizations :</p>
              <%= bl.input :customization_category, collection: (@bike.customization_categories.reject {|cat| cat == cc}), label_method: :bike_element  %>

            </div>
            <%= bl.submit  %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>